from setuptools import setup

setup(
    name='TPM-Financial-Analysis',
    version='',
    packages=['venv.Lib.site-packages.zmq', 'venv.Lib.site-packages.zmq.log', 'venv.Lib.site-packages.zmq.ssh',
              'venv.Lib.site-packages.zmq.auth', 'venv.Lib.site-packages.zmq.auth.asyncio',
              'venv.Lib.site-packages.zmq.green', 'venv.Lib.site-packages.zmq.green.eventloop',
              'venv.Lib.site-packages.zmq.sugar', 'venv.Lib.site-packages.zmq.tests',
              'venv.Lib.site-packages.zmq.tests.asyncio', 'venv.Lib.site-packages.zmq.utils',
              'venv.Lib.site-packages.zmq.asyncio', 'venv.Lib.site-packages.zmq.backend',
              'venv.Lib.site-packages.zmq.backend.cffi', 'venv.Lib.site-packages.zmq.backend.cython',
              'venv.Lib.site-packages.zmq.devices', 'venv.Lib.site-packages.zmq.eventloop',
              'venv.Lib.site-packages.zmq.eventloop.minitornado',
              'venv.Lib.site-packages.zmq.eventloop.minitornado.platform', 'venv.Lib.site-packages.attr',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.lxml', 'venv.Lib.site-packages.lxml.html',
              'venv.Lib.site-packages.lxml.includes', 'venv.Lib.site-packages.lxml.isoschematron',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing._private',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.wrapt', 'venv.Lib.site-packages.bleach', 'venv.Lib.site-packages.bleach._vendor',
              'venv.Lib.site-packages.bleach._vendor.html5lib', 'venv.Lib.site-packages.bleach._vendor.html5lib._trie',
              'venv.Lib.site-packages.bleach._vendor.html5lib.filters',
              'venv.Lib.site-packages.bleach._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.bleach._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.bleach._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.jinja2',
              'venv.Lib.site-packages.pandas', 'venv.Lib.site-packages.pandas.io',
              'venv.Lib.site-packages.pandas.io.sas', 'venv.Lib.site-packages.pandas.io.json',
              'venv.Lib.site-packages.pandas.io.formats', 'venv.Lib.site-packages.pandas.io.msgpack',
              'venv.Lib.site-packages.pandas.io.clipboard', 'venv.Lib.site-packages.pandas.api',
              'venv.Lib.site-packages.pandas.api.types', 'venv.Lib.site-packages.pandas.api.extensions',
              'venv.Lib.site-packages.pandas.core', 'venv.Lib.site-packages.pandas.core.util',
              'venv.Lib.site-packages.pandas.core.tools', 'venv.Lib.site-packages.pandas.core.arrays',
              'venv.Lib.site-packages.pandas.core.dtypes', 'venv.Lib.site-packages.pandas.core.sparse',
              'venv.Lib.site-packages.pandas.core.groupby', 'venv.Lib.site-packages.pandas.core.indexes',
              'venv.Lib.site-packages.pandas.core.reshape', 'venv.Lib.site-packages.pandas.core.internals',
              'venv.Lib.site-packages.pandas.core.computation', 'venv.Lib.site-packages.pandas.util',
              'venv.Lib.site-packages.pandas._libs', 'venv.Lib.site-packages.pandas._libs.tslibs',
              'venv.Lib.site-packages.pandas.tests', 'venv.Lib.site-packages.pandas.tests.io',
              'venv.Lib.site-packages.pandas.tests.io.sas', 'venv.Lib.site-packages.pandas.tests.io.json',
              'venv.Lib.site-packages.pandas.tests.io.parser', 'venv.Lib.site-packages.pandas.tests.io.formats',
              'venv.Lib.site-packages.pandas.tests.io.msgpack', 'venv.Lib.site-packages.pandas.tests.api',
              'venv.Lib.site-packages.pandas.tests.util', 'venv.Lib.site-packages.pandas.tests.frame',
              'venv.Lib.site-packages.pandas.tests.tools', 'venv.Lib.site-packages.pandas.tests.arrays',
              'venv.Lib.site-packages.pandas.tests.arrays.sparse',
              'venv.Lib.site-packages.pandas.tests.arrays.interval',
              'venv.Lib.site-packages.pandas.tests.arrays.categorical', 'venv.Lib.site-packages.pandas.tests.dtypes',
              'venv.Lib.site-packages.pandas.tests.dtypes.cast', 'venv.Lib.site-packages.pandas.tests.scalar',
              'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.multi',
              'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval',
              'venv.Lib.site-packages.pandas.tests.indexing.multiindex', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.resample', 'venv.Lib.site-packages.pandas.tests.extension',
              'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.arrow',
              'venv.Lib.site-packages.pandas.tests.extension.numpy_',
              'venv.Lib.site-packages.pandas.tests.extension.decimal', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.arithmetic', 'venv.Lib.site-packages.pandas.tests.reductions',
              'venv.Lib.site-packages.pandas.tests.computation', 'venv.Lib.site-packages.pandas.arrays',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.tseries',
              'venv.Lib.site-packages.pandas.plotting', 'venv.Lib.site-packages.quandl',
              'venv.Lib.site-packages.quandl.model', 'venv.Lib.site-packages.quandl.utils',
              'venv.Lib.site-packages.quandl.errors', 'venv.Lib.site-packages.quandl.operations',
              'venv.Lib.site-packages.winpty', 'venv.Lib.site-packages.winpty.tests',
              'venv.Lib.site-packages.winpty._winpty', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.IPython',
              'venv.Lib.site-packages.IPython.lib', 'venv.Lib.site-packages.IPython.lib.tests',
              'venv.Lib.site-packages.IPython.core', 'venv.Lib.site-packages.IPython.core.tests',
              'venv.Lib.site-packages.IPython.core.magics', 'venv.Lib.site-packages.IPython.utils',
              'venv.Lib.site-packages.IPython.utils.tests', 'venv.Lib.site-packages.IPython.kernel',
              'venv.Lib.site-packages.IPython.testing', 'venv.Lib.site-packages.IPython.testing.tests',
              'venv.Lib.site-packages.IPython.testing.plugin', 'venv.Lib.site-packages.IPython.external',
              'venv.Lib.site-packages.IPython.external.decorators', 'venv.Lib.site-packages.IPython.terminal',
              'venv.Lib.site-packages.IPython.terminal.tests', 'venv.Lib.site-packages.IPython.terminal.pt_inputhooks',
              'venv.Lib.site-packages.IPython.sphinxext', 'venv.Lib.site-packages.IPython.extensions',
              'venv.Lib.site-packages.IPython.extensions.tests', 'venv.Lib.site-packages.tornado',
              'venv.Lib.site-packages.tornado.test', 'venv.Lib.site-packages.tornado.platform',
              'venv.Lib.site-packages.urllib3', 'venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.urllib3.contrib', 'venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.urllib3.packages', 'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.wcwidth',
              'venv.Lib.site-packages.wcwidth.tests', 'venv.Lib.site-packages.colorama',
              'venv.Lib.site-packages.dateutil', 'venv.Lib.site-packages.dateutil.tz',
              'venv.Lib.site-packages.dateutil.parser', 'venv.Lib.site-packages.dateutil.zoneinfo',
              'venv.Lib.site-packages.nbformat', 'venv.Lib.site-packages.nbformat.v1',
              'venv.Lib.site-packages.nbformat.v1.tests', 'venv.Lib.site-packages.nbformat.v2',
              'venv.Lib.site-packages.nbformat.v2.tests', 'venv.Lib.site-packages.nbformat.v3',
              'venv.Lib.site-packages.nbformat.v3.tests', 'venv.Lib.site-packages.nbformat.v4',
              'venv.Lib.site-packages.nbformat.v4.tests', 'venv.Lib.site-packages.nbformat.tests',
              'venv.Lib.site-packages.notebook', 'venv.Lib.site-packages.notebook.auth',
              'venv.Lib.site-packages.notebook.auth.tests', 'venv.Lib.site-packages.notebook.base',
              'venv.Lib.site-packages.notebook.edit', 'venv.Lib.site-packages.notebook.i18n',
              'venv.Lib.site-packages.notebook.tree', 'venv.Lib.site-packages.notebook.tree.tests',
              'venv.Lib.site-packages.notebook.view', 'venv.Lib.site-packages.notebook.files',
              'venv.Lib.site-packages.notebook.tests', 'venv.Lib.site-packages.notebook.tests.selenium',
              'venv.Lib.site-packages.notebook.bundler', 'venv.Lib.site-packages.notebook.bundler.tests',
              'venv.Lib.site-packages.notebook.notebook', 'venv.Lib.site-packages.notebook.services',
              'venv.Lib.site-packages.notebook.services.api', 'venv.Lib.site-packages.notebook.services.api.tests',
              'venv.Lib.site-packages.notebook.services.config',
              'venv.Lib.site-packages.notebook.services.config.tests',
              'venv.Lib.site-packages.notebook.services.kernels',
              'venv.Lib.site-packages.notebook.services.kernels.tests',
              'venv.Lib.site-packages.notebook.services.contents',
              'venv.Lib.site-packages.notebook.services.contents.tests',
              'venv.Lib.site-packages.notebook.services.security', 'venv.Lib.site-packages.notebook.services.sessions',
              'venv.Lib.site-packages.notebook.services.sessions.tests',
              'venv.Lib.site-packages.notebook.services.nbconvert',
              'venv.Lib.site-packages.notebook.services.nbconvert.tests',
              'venv.Lib.site-packages.notebook.services.kernelspecs',
              'venv.Lib.site-packages.notebook.services.kernelspecs.tests', 'venv.Lib.site-packages.notebook.terminal',
              'venv.Lib.site-packages.notebook.nbconvert', 'venv.Lib.site-packages.notebook.nbconvert.tests',
              'venv.Lib.site-packages.notebook.kernelspecs', 'venv.Lib.site-packages.pygments',
              'venv.Lib.site-packages.pygments.lexers', 'venv.Lib.site-packages.pygments.styles',
              'venv.Lib.site-packages.pygments.filters', 'venv.Lib.site-packages.pygments.formatters',
              'venv.Lib.site-packages.requests', 'venv.Lib.site-packages.testpath', 'venv.Lib.site-packages.ipykernel',
              'venv.Lib.site-packages.ipykernel.gui', 'venv.Lib.site-packages.ipykernel.comm',
              'venv.Lib.site-packages.ipykernel.pylab', 'venv.Lib.site-packages.ipykernel.tests',
              'venv.Lib.site-packages.ipykernel.inprocess', 'venv.Lib.site-packages.ipykernel.inprocess.tests',
              'venv.Lib.site-packages.nbconvert', 'venv.Lib.site-packages.nbconvert.tests',
              'venv.Lib.site-packages.nbconvert.utils', 'venv.Lib.site-packages.nbconvert.utils.tests',
              'venv.Lib.site-packages.nbconvert.filters', 'venv.Lib.site-packages.nbconvert.filters.tests',
              'venv.Lib.site-packages.nbconvert.writers', 'venv.Lib.site-packages.nbconvert.writers.tests',
              'venv.Lib.site-packages.nbconvert.exporters', 'venv.Lib.site-packages.nbconvert.exporters.tests',
              'venv.Lib.site-packages.nbconvert.resources', 'venv.Lib.site-packages.nbconvert.preprocessors',
              'venv.Lib.site-packages.nbconvert.preprocessors.tests', 'venv.Lib.site-packages.nbconvert.postprocessors',
              'venv.Lib.site-packages.nbconvert.postprocessors.tests', 'venv.Lib.site-packages.qtconsole',
              'venv.Lib.site-packages.qtconsole.tests', 'venv.Lib.site-packages.terminado',
              'venv.Lib.site-packages.terminado.tests', 'venv.Lib.site-packages.traitlets',
              'venv.Lib.site-packages.traitlets.tests', 'venv.Lib.site-packages.traitlets.utils',
              'venv.Lib.site-packages.traitlets.utils.tests', 'venv.Lib.site-packages.traitlets.config',
              'venv.Lib.site-packages.traitlets.config.tests', 'venv.Lib.site-packages.defusedxml',
              'venv.Lib.site-packages.ipywidgets', 'venv.Lib.site-packages.ipywidgets.tests',
              'venv.Lib.site-packages.ipywidgets.widgets', 'venv.Lib.site-packages.ipywidgets.widgets.tests',
              'venv.Lib.site-packages.jsonschema', 'venv.Lib.site-packages.jsonschema.tests',
              'venv.Lib.site-packages.jsonschema.benchmarks', 'venv.Lib.site-packages.markupsafe',
              'venv.Lib.site-packages.matplotlib', 'venv.Lib.site-packages.matplotlib.tri',
              'venv.Lib.site-packages.matplotlib.axes', 'venv.Lib.site-packages.matplotlib.cbook',
              'venv.Lib.site-packages.matplotlib.style', 'venv.Lib.site-packages.matplotlib.compat',
              'venv.Lib.site-packages.matplotlib.testing', 'venv.Lib.site-packages.matplotlib.testing.jpl_units',
              'venv.Lib.site-packages.matplotlib.backends', 'venv.Lib.site-packages.matplotlib.backends.qt_editor',
              'venv.Lib.site-packages.matplotlib.sphinxext', 'venv.Lib.site-packages.matplotlib.projections',
              'venv.Lib.site-packages.pyrsistent', 'venv.Lib.site-packages.send2trash',
              'venv.Lib.site-packages.jupyter_core', 'venv.Lib.site-packages.jupyter_core.tests',
              'venv.Lib.site-packages.jupyter_core.utils', 'venv.Lib.site-packages.mpl_toolkits.mplot3d',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid', 'venv.Lib.site-packages.mpl_toolkits.axes_grid1',
              'venv.Lib.site-packages.mpl_toolkits.axisartist', 'venv.Lib.site-packages.webencodings',
              'venv.Lib.site-packages.jupyter_client', 'venv.Lib.site-packages.jupyter_client.tests',
              'venv.Lib.site-packages.jupyter_client.ioloop', 'venv.Lib.site-packages.jupyter_client.blocking',
              'venv.Lib.site-packages.more_itertools', 'venv.Lib.site-packages.more_itertools.tests',
              'venv.Lib.site-packages.prompt_toolkit', 'venv.Lib.site-packages.prompt_toolkit.layout',
              'venv.Lib.site-packages.prompt_toolkit.styles', 'venv.Lib.site-packages.prompt_toolkit.contrib',
              'venv.Lib.site-packages.prompt_toolkit.contrib.telnet',
              'venv.Lib.site-packages.prompt_toolkit.contrib.completers',
              'venv.Lib.site-packages.prompt_toolkit.contrib.validators',
              'venv.Lib.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.Lib.site-packages.prompt_toolkit.filters', 'venv.Lib.site-packages.prompt_toolkit.terminal',
              'venv.Lib.site-packages.prompt_toolkit.clipboard', 'venv.Lib.site-packages.prompt_toolkit.eventloop',
              'venv.Lib.site-packages.prompt_toolkit.key_binding',
              'venv.Lib.site-packages.prompt_toolkit.key_binding.bindings', 'venv.Lib.site-packages.jupyter_console',
              'venv.Lib.site-packages.jupyter_console.tests', 'venv.Lib.site-packages.ipython_genutils',
              'venv.Lib.site-packages.ipython_genutils.tests', 'venv.Lib.site-packages.ipython_genutils.testing',
              'venv.Lib.site-packages.pandas_datareader', 'venv.Lib.site-packages.pandas_datareader.av',
              'venv.Lib.site-packages.pandas_datareader.io', 'venv.Lib.site-packages.pandas_datareader.iex',
              'venv.Lib.site-packages.pandas_datareader.mstar', 'venv.Lib.site-packages.pandas_datareader.tests',
              'venv.Lib.site-packages.pandas_datareader.tests.av', 'venv.Lib.site-packages.pandas_datareader.tests.io',
              'venv.Lib.site-packages.pandas_datareader.tests.mstar',
              'venv.Lib.site-packages.pandas_datareader.tests.yahoo',
              'venv.Lib.site-packages.pandas_datareader.tests.google', 'venv.Lib.site-packages.pandas_datareader.yahoo',
              'venv.Lib.site-packages.pandas_datareader.compat', 'venv.Lib.site-packages.pandas_datareader.google',
              'venv.Lib.site-packages.prometheus_client', 'venv.Lib.site-packages.prometheus_client.bridge',
              'venv.Lib.site-packages.prometheus_client.twisted',
              'venv.Lib.site-packages.prometheus_client.openmetrics', 'venv.Lib.site-packages.widgetsnbextension',
              'venv.Lib.site-packages.win_unicode_console', 'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations', 'GetData'],
    url='',
    license='',
    author='TPM',
    author_email='Thepythonmentor@gmail.com',
    description='Financial data analysis '
)
